version: '2'
services:

  bot:
    build:
      context: ./../
      dockerfile: build/package/Dockerfile
    depends_on:
      - goose
    environment:
      - TG_TOKEN
    command: ["./main"]

  goose:
    build:
      context: ./../
      dockerfile: build/migrations/Dockerfile
    depends_on:
      - postgres
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432

  postgres:
    image: "postgres:11.4"
    environment:
      POSTGRES_DB: "vocab"
    ports:
      - "5432:5432"