version: '2'
services:

  bot:
    build:
      context: ./../
      dockerfile: build/package/Dockerfile
    depends_on:
      - goose
    environment:
      - TG_TOKEN
    command: ["./main"]

  goose:
    build:
      context: ./../
      dockerfile: build/migrations/Dockerfile
    volumes:
      - ./../sql/migrations:/sql
    depends_on:
      - postgres
    command: ["/wait-for-postgres.sh", "postgres"]

  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: "vocab"
    ports:
      - "5432:5432"