version: '2'
services:
  bot:
    build:
      context: ./../
      dockerfile: build/package/Dockerfile
    depends_on:
      - postgres
    environment:
      - TG_TOKEN
  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: "vocab"
    ports:
      - "5432:5432"